# Generated by Django 4.1.7 on 2023-03-08 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_staff_notification_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff_notification',
            name='status',
        ),
        migrations.AddField(
            model_name='staff_notification',
            name='status1',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
