# Generated by Django 4.1.5 on 2023-03-08 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_subject_created_at'),
        ('app', '0008_remove_staff_notification_status_and_more'),
    ]

    operations = [
    ]
