# Generated by Django 4.1.5 on 2023-03-08 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_merge_20230308_1732'),
        ('app', '0010_remove_staff_notification_status1_and_more'),
    ]

    operations = [
    ]
