# Generated by Django 4.1.7 on 2023-03-18 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_staff_feedback'),
        ('app', '0014_merge_20230318_2117'),
    ]

    operations = [
    ]
