# Generated by Django 4.1.5 on 2023-03-22 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_studentresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_notification',
            name='status',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='subject_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_result_subject_id', to='app.subject'),
        ),
    ]
